service: re-release-radar
provider:
 name: aws
 runtime: python3.10
 stage: dev
 region: ap-southeast-2
 memorySize: 128
plugins:
 - serverless-wsgi
 - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
  cronRefreshPlaylist:
   handler: app.auto_refresh_playlist
   events:
     - schedule: rate(2 minutes)
  app:
    handler: "wsgi_handler.handler"
    timeout: 60
    environment:
      SPOTIPY_CLIENT_ID: ${file(./config.${opt:stage, 'dev'}.json):SPOTIPY_CLIENT_ID}
      SPOTIPY_CLIENT_SECRET: ${file(./config.${opt:stage, 'dev'}.json):SPOTIPY_CLIENT_SECRET}
      SPOTIPY_REDIRECT_URI: ${file(./config.${opt:stage, 'dev'}.json):SPOTIPY_REDIRECT_URI}
      FLASK_CONFIG: ${file(./config.${opt:stage, 'dev'}.json):FLASK_CONFIG}
      FLASK_APP: ${file(./config.${opt:stage, 'dev'}.json):FLASK_APP}
      STAGE: ${file(./config.${opt:stage, 'dev'}.json):STAGE}
      SESSION_SECRET_KEY: ${file(./config.${opt:stage, 'dev'}.json):SESSION_SECRET_KEY}
      REQUIRED_SCOPES: ${file(./config.${opt:stage, 'dev'}.json):REQUIRED_SCOPES}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'